// <auto-generated />
using System;
using FinancialAppAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinancialAppAPI.Migrations
{
    [DbContext(typeof(FinancialContext))]
    [Migration("20220804194028_CreateIncomeAndExpenseTables")]
    partial class CreateIncomeAndExpenseTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FinancialAppAPI.Models.Expense", b =>
                {
                    b.Property<int>("expenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("expenseId"), 1L, 1);

                    b.Property<double>("expenseAmount")
                        .HasColumnType("float");

                    b.Property<DateTime>("expenseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("expenseName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("expenseId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("FinancialAppAPI.Models.Income", b =>
                {
                    b.Property<int>("incomeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("incomeId"), 1L, 1);

                    b.Property<double>("incomeAmount")
                        .HasColumnType("float");

                    b.Property<DateTime>("incomeDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("incomeName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("incomeId");

                    b.ToTable("Incomes");
                });
#pragma warning restore 612, 618
        }
    }
}
